Add a new result.yml (#1)
* Add a new result.yml

* Result as reusable

* New iteration

* New iteration

* New iteration

* New iteration

* New iteration

* New iteration

* New iteration

* New iteration

* New iteration

* New iteration

* Fail result job2 if detected

* OMG

* New iteration

* New iteration

* New iteration

* New iteration

* New iteration

* New iteration

* New iteration

* New iteration

* New iteration

* New iteration

* Test this new pattern in dynamic_matrix

* New iteration

* New iteration

* New iteration

* New iteration

* New iteration

* Disable matrix

diff --git a/.github/workflows/dynamic_matrix.yml b/.github/workflows/dynamic_matrix.yml
--- a/.github/workflows/dynamic_matrix.yml
+++ b/.github/workflows/dynamic_matrix.yml
@@ -34,8 +34,11 @@ jobs:
     strategy:
       fail-fast: false
       matrix: ${{fromJson(needs.pre_workflow.outputs.matrix)}}
+    outputs:
+      failed: ${{ steps.prepare_artifact.outputs.failed }}
     steps:
       - name: Main action
+        id: main_action
         shell: bash
         env:
           NODE_INDEX: ${{ matrix.node_index }}
@@ -65,6 +68,12 @@ jobs:
 
           echo "artifact_name=$artifact" >> $GITHUB_OUTPUT
           echo "artifact_path=$artifact.zip" >> $GITHUB_OUTPUT
+          echo "${{ steps.main_action.outcome }} = failure?"
+          if [ ${{ steps.main_action.outcome }} = "failure" ]; then
+            echo "failed=true" >> $GITHUB_OUTPUT
+          else
+            echo "failed=false" >> $GITHUB_OUTPUT
+          fi
 
       - name: Publish artifact
         if: always()
@@ -78,6 +87,8 @@ jobs:
     needs: workflow
     runs-on: ubuntu-latest
     steps:
+      - run: echo '${{ toJSON(needs) }}'
+
       - uses: actions/download-artifact@v3
         id: download_artifacts
         with: # TODO: find an equivalent not downloading ALL ARTIFACTS
@@ -87,43 +98,45 @@ jobs:
         id: resolve_artifacts
         shell: bash
         run: |
-          echo ">> Root of artifacts folder"
           directory="${{ steps.download_artifacts.outputs.download-path }}"
 
-          printf "\n>> Only keep artifacts for the given key\n"
+          echo "::group::Only keep artifacts for the given key"
           for artifact in $(ls "$directory"); do
             if [[ $artifact =~ "^${{ inputs.key }}.*" ]]; then
               echo "Remove $artifact" && rm -rf "$directory/$artifact"
             fi
           done
+          echo "::endgroup::"
 
-          printf "\n>> Extract-Remove all zip files\n" # Exp: artifacts/Value-1-2/Value-1-2.zip
+          echo "::group::Extract and remove all zip files" # Exp: artifacts/Value-1-2/Value-1-2.zip
           find "$directory" -type f -name "*.zip" | while read artifact_zip; do
             artifact_dir="$(dirname $artifact_zip)"
             echo "Extract $artifact_zip in $artifact_dir"
             unzip "$artifact_zip" -d "$artifact_dir"
             rm "$artifact_zip"
           done
+          echo "::endgroup::"
 
-          printf "\n>> Consume artifacts\n"
-          failed=false
+          echo "::group::Consume artifacts"
           find "$directory" -type f | while read artifact; do
             echo "Content of $artifact: $(cat $artifact)"
-            if true; then # TODO: put your custom logic here
-              failed=true
-            fi
           done
+          echo "::endgroup::"
 
-          echo "failed=$failed" >> $GITHUB_OUTPUT
+          if [ ${{ inputs.key }} == 'debug' ]; then
+            echo "failed=true" | tee $GITHUB_OUTPUT
+          else
+            echo "failed=false" | tee $GITHUB_OUTPUT
+          fi
 
       - name: Delete all consumed artifacts
         uses: jimschubert/delete-artifacts-action@v1
         with:
           pattern: "^${{ inputs.key }}.*"
 
-      - name: Fail workflow if condition
+      - name: Fail if failed detected
         # Neither == true or == 'true' worked...
         # https://github.com/actions/runner/issues/1483
-        if: ${{ steps.resolve_artifacts.outputs.failed }}
+        if: ${{ steps.resolve_artifacts.outputs.failed == 'true' }}
         shell: bash
-        run: echo "Fail the workflow considering consumed workflow failed" && exit 1
+        run: exit 1
